# Generated by Django 5.2.11 on 2026-02-08 11:27

from django.db import migrations


def cleanup_duplicate_oauth_apps(apps, schema_editor):
    """
    Remove duplicate Google OAuth SocialApp entries from database.
    We use settings-based OAuth configuration, so database entries are not needed.
    """
    try:
        # Get SocialApp model
        SocialApp = apps.get_model('socialaccount', 'SocialApp')
        
        # Find all Google OAuth apps
        google_apps = SocialApp.objects.filter(provider='google')
        count = google_apps.count()
        
        if count > 0:
            # Delete all of them since we use settings-based config
            google_apps.delete()
            print(f"Cleaned up {count} duplicate Google OAuth SocialApp entries")
    except Exception as e:
        # Don't fail migration if SocialApp doesn't exist yet
        print(f"Could not clean up OAuth apps: {e}")


def reverse_cleanup(apps, schema_editor):
    """
    Reverse migration - no action needed as we can't restore deleted entries.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_car_is_sold'),
        ('socialaccount', '__latest__'),  # Ensure allauth tables exist
    ]

    operations = [
        migrations.RunPython(cleanup_duplicate_oauth_apps, reverse_cleanup),
    ]
