# Generated by Django 5.2.11 on 2026-02-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cleanup_duplicate_oauth_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
