# Generated by Django 5.2.11 on 2026-02-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_increase_token_field_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecar',
            name='car_id',
            field=models.CharField(help_text='InstantDB car post ID', max_length=255),
        ),
    ]
