# Generated by Django 5.2.11 on 2026-02-08 11:45

from django.db import migrations, connection


def force_alter_varchar_fields(apps, schema_editor):
    """
    Force alter VARCHAR fields to 255 characters.
    Only runs on PostgreSQL (Vercel production).
    """
    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            # UserProfile token fields
            cursor.execute(
                'ALTER TABLE store_userprofile ALTER COLUMN verification_token TYPE VARCHAR(255);'
            )
            cursor.execute(
                'ALTER TABLE store_userprofile ALTER COLUMN reset_token TYPE VARCHAR(255);'
            )
            # FavoriteCar car_id field
            cursor.execute(
                'ALTER TABLE store_favoritecar ALTER COLUMN car_id TYPE VARCHAR(255);'
            )
        print("Successfully altered VARCHAR fields to 255 characters")
    else:
        print(f"Skipping VARCHAR alterations - running on {connection.vendor}, not PostgreSQL")


def reverse_alter_varchar_fields(apps, schema_editor):
    """Reverse the VARCHAR field alterations."""
    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            cursor.execute(
                'ALTER TABLE store_userprofile ALTER COLUMN verification_token TYPE VARCHAR(100);'
            )
            cursor.execute(
                'ALTER TABLE store_userprofile ALTER COLUMN reset_token TYPE VARCHAR(100);'
            )
            cursor.execute(
                'ALTER TABLE store_favoritecar ALTER COLUMN car_id TYPE VARCHAR(100);'
            )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_favoritecar_car_id'),
    ]

    operations = [
        migrations.RunPython(force_alter_varchar_fields, reverse_alter_varchar_fields),
    ]
