# Generated by Django 5.2.11 on 2026-02-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_force_fix_varchar_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide this car from public inventory'),
        ),
    ]
